name: Dan’s world
description: Android developer
meta_description: “Android developer”

aboutPage: true

markdown: redcarpet
highlighter: pygments

paginate: 20
baseurl: /
domain_name: 'http://shinado.github.io'
google_analytics: 'UA-XXXXXXXX-X'
disqus: false
disqus_shortname: ‘ss’

# Details for the RSS feed generator
url:            http://shinado.github.io
author:         Dan
authorTwitter:  shinado023

permalink:       /:year/:title/

defaults:
    -
        scope:
            path: "" # empty string for all files
            type: pages
        values:
            layout: default
    -
        scope:
            path: "" # empty string for all files
            type: posts
        values:
            layout: post
    -
        scope:
            path: ""
            type: drafts
        values:
            layout: post
