# Dependencies
markdown:            kramdown
highlighter:         rouge

# Gems (for Jekyll 3.0)
gems: [jekyll-paginate]

# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty

# Setup
title:               Aris Launcher
tagline:             ‘The New Android Launcher’
description:         ''
url:                 http://www.arislauncher.com
baseurl:             http://www.arislauncher.com/
paginate:            7

# About/contact
author:
  name:              Daniel Ng
  url:               https://twitter.com/shinado023
  email:             shinado023@gmail.com

# Custom vars
version:             2.0

# Social Media
github:				http://github.com/shinado
twitter:			http://twitter.com/shinado023
disqus:             h

# Theme Author (Please don't edit this line cause of MIT LICENSE rules)
theme:
  creator:			Rizky Ariestiyansyah
  codename:			Naringu
  link:             https://github.com/ariestiyansyah/naringu
