# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Aris Launcher
email: shinado023@gmail.com

#write html inside the double quotes to display in jumbotron
description: "<h3>Hey guys, this is</h3><h1>Aris Launcher</h1><h3>The New Android Launcher</h3>"


baseurl: "" # the subpath of your site, e.g. /blog
url: "http://shinado.github.io" # the base hostname & protocol for your site
twitter_username: shinado023
github_username:  shinado

# Build settings
markdown: kramdown
